### PR TITLE
adding illustrative example of loading a Zarr into Xarray from an IPLD mapper

### PR DESCRIPTION
**Pull request by rbanick**
Adding an example use case we’ve pieced together that we believe is repeatable, easy, and of value to others.

### CODE REVIEW

**Comment by d70-t** [comment]
Cool, thanks for the PR! That's a very nice (and missing example). I'm just wondering where exactly to put it, and probably I'd put it just after "storing on IPFS". The latter parts only cover usage independent of IPFS and I like to have both, but with a clear visual distinction.

Then there's the CI, which has some critics about the examples... Can you have a look at those? You can run the tests locally using `tox` as well.

**Comment by rbanick** [comment]
Agreed on the placement of the example, it’s nice to have it immediately following the `to_zarr`. Feel free to swap in the example hash you used and the corresponding Xarray — I used one of mine just to show a more “real life” Xarray dataset.

On the tests — hmm. Will check.

**Comment by rbanick** [comment]
`print(cid_obj)` just gives back the hash — I need to call `cid_obj` directly to see the base32 representation. Oops! Tests now pass and the example has been moved under “Storing on IPFS”

**Comment by rbanick** [comment]
So we are in the midst of pushing up and pulling down datasets to IPFS as we figure out how continuously updating Zarrs can work on our stack. In ~2 months I will absolutely have some "stable" Zarrs we can point to and would love to include them. Can we use this hash as a placeholder until then?

**Comment by d70-t** [comment]
Sure, that's fine!

**Pull request merged**
